name: Auto Approve and Merge Updates
run-name: Auto Approve and Merge Updates

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Approve dependabot pr
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for dependabot pr
        run: gh pr merge --auto --rebase "${{github.event.pull_request.html_url}}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
